# Generated by Django 3.2.12 on 2022-10-17 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0006_auto_20221017_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='TekKategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='urun',
            name='tek',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.tekkategori'),
        ),
    ]
