# Generated by Django 3.2.12 on 2022-10-19 08:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunler', '0007_auto_20221017_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='aciklama',
            field=ckeditor.fields.RichTextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='tek',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='urunler.tekkategori'),
        ),
    ]
